// Run with Playwright in NODE_PATH; all event data is local test data.
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),event=require('../server/tournament.cjs').EVENT;
let data={ok:true,event,server_now:event.start_at-1000,phase:'scheduled',leaders:[],winners:[],outages:[],results_provisional:true};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/api/public/tournament'){res.setHeader('content-type','application/json');res.end(JSON.stringify(data));return;}
 const base=path.join(root,'server/public'),pathname=url.pathname==='/tournament'?'tournament.html':url.pathname==='/'?'index.html':url.pathname.slice(1),file=path.resolve(base,pathname);if(!file.startsWith(base+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('content-type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 try{const page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.goto('http://127.0.0.1:'+server.address().port+'/tournament');await page.waitForFunction(()=>document.querySelector('#event-schedule').textContent.includes('CDT'));
 await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('nav a[href="/tournament"]').count(),1);assert.equal(await page.locator('#clock-label').textContent(),'Starts in');data.server_now=event.start_at;data.phase='live';await page.clock.runFor(2200);assert.equal(await page.locator('#event-phase').textContent(),'LIVE');
 assert.deepEqual(await page.locator('.event-prizes strong').allTextContents(),['$250 USD','$125 USD','$75 USD','$37 USD','$13 USD']);
 data={...data,server_now:event.end_at,phase:'ended',leaders:[{rank:1,persona:'Player <One>',net_rr:150,wins:5,matches:6}],winners:[{rank:1,persona:'Player <One>',net_rr:150,prize_usd:250}]};await page.reload();await page.locator('.event-winner').waitFor();assert.equal(await page.locator('#winners-note').textContent(),'Provisional results — under review.');assert.equal(await page.locator('#event-winners script').count(),0);assert.equal(await page.locator('.event-winner strong').textContent(),'$250 USD');
 for(const width of [1400,800,390]){await page.setViewportSize({width,height:1000});assert(await page.locator('nav a[href="/tournament"]').isVisible());assert(await page.locator('nav a[href="/account"]').isVisible(),'Create account must remain available');assert(await page.locator('.event-winner').isVisible());const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,'website overflows at '+width+': '+JSON.stringify(await page.evaluate(()=>Array.from(document.querySelectorAll('body *')).filter(n=>n.getBoundingClientRect().right>innerWidth+1).map(n=>({tag:n.tagName,id:n.id,cls:n.className,right:n.getBoundingClientRect().right})).slice(0,10))));}
 data.results_provisional=false;data.winners=[250,125,75,37,13,13].map((prize_usd,i)=>({rank:Math.min(i+1,5),persona:'Winner '+i,net_rr:100-Math.min(i,4),prize_usd}));await page.reload();await page.waitForFunction(()=>document.querySelector('#winners-note').textContent==='Winners confirmed.');
 assert.equal(await page.locator('.event-winner').count(),6);assert.deepEqual(await page.locator('.event-winner strong').allTextContents(),['$250 USD','$125 USD','$75 USD','$37 USD','$13 USD','$13 USD']);
 for(const width of [1400,800,390]){await page.setViewportSize({width,height:1000});assert(await page.locator('.event-winner').last().isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'tied winners overflow at '+width);}
 assert.deepEqual(errors,[]);await page.setViewportSize({width:1400,height:1000});fs.mkdirSync(path.join(root,'build'),{recursive:true});await page.screenshot({path:path.join(root,'build/tournament-website.png')});console.log('Tournament website: mobile layout, automatic start, provisional and confirmed tied winners passed.');
 }finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
