"""Host-migration callbacks and private authority transport; generated by make_blueprints.py."""
from ctf_graphs import G, P, SYS, MATH, STR, GS_LIB, CONTROLLER, ACTOR, GM_PARENT
import bb5_graphs as B
import combat_graphs as combat

HMS = '/Script/HostMigrationSystem.HMS_GameMode'
HMS_GI = '/Script/HostMigrationSystem.HMS_GameInstance'
SETTINGS = '/Script/HostMigrationSystem.HMS_MigrationSettings'
REQUEST = B.BB5_DIR + '/BP_BB5MigrationRequest.BP_BB5MigrationRequest_C'
DURABLE = ('CompetitiveStarted', 'StartApprovedRoster', 'StartApprovedMatch', 'StartApprovedHumans',
           'PresenceDirty', 'LatchTeam', 'LatchSide', 'LatchObjectiveTeam', 'bLatched',
           'FinalPending', 'FinalAcknowledged', 'FinalCaptured', 'FinalBatch', 'FinalMeta',
           'FinalMatch', 'FinalCombat', 'HostEpoch')

def gi_timeout(g, p):
    g.call(p+'gi', GS_LIB, 'GetGameInstance')
    g.cast(p+'cast', HMS_GI, pure=True); g.link((p+'gi.ReturnValue',p+'cast.cast_object'))
    g.set(p+'timeout', 'HMS_ReconnectTimeoutSeconds', HMS_GI, defaults={'HMS_ReconnectTimeoutSeconds':'300.0'})
    g.link((p+'cast.cast_result',p+'timeout.self'))
    return p+'timeout'

def events(g):
    g.custom('migration_tick', 'MigrationTick')
    g.custom('migration_advertise', 'MigrationAdvertise')
    g.custom('migration_finish', 'MigrationFinishIfEnded')

def logic(g):
    g.get('migration_rule','BB5BombRule')
    g.get('migration_settings','HMS_MigrationSettings',HMS)
    g.n('migration_timeout','setmembers',struct=SETTINGS,field='PreviousPlayersReconnectTimeout',
        defaults={'PreviousPlayersReconnectTimeout':'300.0'})
    g.link(('migration_settings.HMS_MigrationSettings','migration_timeout.StructRef'))
    g.call('t_migration',SYS,'K2_SetTimer',{'FunctionName':'MigrationTick','Time':'2.0','bLooping':'true'})
    g.selfnode('migration_self');g.link(('migration_self.self','t_migration.Object'))
    g.link(('migration_self.self','migration_settings.self'))
    g.chain('migration_timeout','t_migration')

    # A completed engine save nominates the successor. A local client cannot elect itself.
    g.event('migration_saved','HMS_OnCreateGameSaveTaskComplete',HMS)
    g.callparent('migration_saved_parent',GM_PARENT,'HMS_OnCreateGameSaveTaskComplete')
    g.chain('migration_saved','migration_saved_parent')
    g.get('migration_candidate','HMS_CurrentChosenNewHost',HMS)
    g.link(('migration_self.self','migration_candidate.self'))
    g.call('migration_valid',SYS,'IsValid');g.link(('migration_candidate.HMS_CurrentChosenNewHost','migration_valid.Object'))
    g.branch('migration_candidate_valid');g.link(('migration_valid.ReturnValue','migration_candidate_valid.condition'))
    g.chain('migration_saved_parent','migration_candidate_valid')
    g.get('migration_candidate_ps','PlayerState',CONTROLLER)
    g.link(('migration_candidate.HMS_CurrentChosenNewHost','migration_candidate_ps.self'))
    g.call('migration_candidate_id',B.ONLINE,'RetrievePlatformIdAsStringFromPlayerState')
    g.link(('migration_candidate_ps.PlayerState','migration_candidate_id.PlayerState'))
    g.set('migration_remember','MigrationCandidate',B.RULE)
    g.link(('migration_rule.BB5BombRule','migration_remember.self'),('migration_candidate_id.ReturnValue','migration_remember.MigrationCandidate'))
    g.chain('migration_candidate_valid','migration_remember')
    g.set('migration_clear_candidate','MigrationCandidate',B.RULE,defaults={'MigrationCandidate':''})
    g.link(('migration_rule.BB5BombRule','migration_clear_candidate.self'),('migration_candidate_valid.else','migration_clear_candidate.exec'))
    g.call('migration_send_now',None,'MigrationTick');g.chain('migration_remember','migration_send_now')

    # Set waiting BEFORE the parent's warmup transition. A repeated callback cannot
    # increment authority twice or clear an already established reconnect window.
    g.event('migration_restored','HMS_OnGameRehosted',HMS)
    g.get('migration_seen','MigrationCallbackSeen',B.RULE);g.link(('migration_rule.BB5BombRule','migration_seen.self'))
    g.branch('migration_once');g.link(('migration_seen.MigrationCallbackSeen','migration_once.condition'))
    g.chain('migration_restored','migration_once')
    previous='migration_once.else'
    for name,value in (('MigrationCallbackSeen','true'),('MigrationPending','true'),('PresenceDirty','true'),
                       ('CompetitiveStarted','true'),('FinalCaptured','false')):
        node='migration_set_'+name;g.set(node,name,B.RULE,defaults={name:value})
        g.link(('migration_rule.BB5BombRule',node+'.self'),(previous,node+'.exec'));previous=node+'.then'
    g.get('migration_epoch','HostEpoch',B.RULE);g.link(('migration_rule.BB5BombRule','migration_epoch.self'))
    g.call('migration_next_epoch',MATH,'Add_IntInt',{'B':'1'});g.link(('migration_epoch.HostEpoch','migration_next_epoch.A'))
    g.set('migration_set_epoch','HostEpoch',B.RULE)
    g.link(('migration_rule.BB5BombRule','migration_set_epoch.self'),('migration_next_epoch.ReturnValue','migration_set_epoch.HostEpoch'),(previous,'migration_set_epoch.exec'))
    g.callparent('migration_parent',GM_PARENT,'HMS_OnGameRehosted');g.chain('migration_set_epoch','migration_parent')
    g.call('migration_activate',None,'MigrationTick');g.chain('migration_parent','migration_activate')

    g.existing('migration_tick','MigrationTick')
    key,ranked=B._start_key(g,'migration_key_')
    g.branch('migration_ranked');g.link((ranked,'migration_ranked.condition'));g.chain('migration_tick','migration_ranked')
    g.call('migration_transform',MATH,'MakeTransform');g.spawn('migration_request',REQUEST)
    g.link(('migration_transform.ReturnValue','migration_request.SpawnTransform'));g.chain('migration_ranked','migration_request')
    g.call('migration_begin',REQUEST,'BeginMigrationRequest')
    g.link(('migration_request.ReturnValue','migration_begin.self'),('migration_rule.BB5BombRule','migration_begin.RuleComponent'),(key,'migration_begin.MatchKey'))
    g.chain('migration_request','migration_begin')
    g.get('migration_pending','MigrationPending',B.RULE);g.link(('migration_rule.BB5BombRule','migration_pending.self'))
    g.call('migration_ready',MATH,'Not_PreBool');g.link(('migration_pending.MigrationPending','migration_ready.A'))
    g.call('migration_has_epoch',MATH,'Greater_IntInt',{'B':'0'});g.link(('migration_epoch.HostEpoch','migration_has_epoch.A'))
    g.call('migration_publish_ready',MATH,'BooleanAND');g.link(('migration_ready.ReturnValue','migration_publish_ready.A'),('migration_has_epoch.ReturnValue','migration_publish_ready.B'))
    g.branch('migration_retry_advertise');g.link(('migration_publish_ready.ReturnValue','migration_retry_advertise.condition'));g.chain('migration_begin','migration_retry_advertise')
    g.call('migration_retry_publish',None,'MigrationAdvertise');g.chain('migration_retry_advertise','migration_retry_publish')
    g.call('migration_retry_finish',None,'MigrationFinishIfEnded');g.chain('migration_retry_publish','migration_retry_finish')

    # A restored EndMatch need not fire OnMatchEnded or OnRoundStarted again.
    # Close the fresh collector explicitly; its terminal marker is retryable and
    # idempotent. Tick also retries if the collector has not yet been created.
    g.existing('migration_finish','MigrationFinishIfEnded')
    g.get('migration_final_pending','FinalPending',B.RULE);g.link(('migration_rule.BB5BombRule','migration_final_pending.self'))
    g.call('migration_gs',GS_LIB,'GetGameState');g.cast('migration_gsc',B.BC_GS,pure=True);g.link(('migration_gs.ReturnValue','migration_gsc.cast_object'))
    g.call('migration_phase',B.BC_GS,'GetCurrentPhase');g.link(('migration_gsc.cast_result','migration_phase.self'))
    g.call('migration_phase_string','/Script/GameplayTags.BlueprintGameplayTagLibrary','GetTagName');g.link(('migration_phase.ReturnValue','migration_phase_string.GameplayTag'))
    g.call('migration_phase_text',STR,'Conv_NameToString');g.link(('migration_phase_string.ReturnValue','migration_phase_text.InName'))
    g.call('migration_ended',STR,'EqualEqual_StrStr',{'B':'Game.Phase.EndMatch'});g.link(('migration_phase_text.ReturnValue','migration_ended.A'))
    g.call('migration_terminal',MATH,'BooleanOR');g.link(('migration_ended.ReturnValue','migration_terminal.A'),('migration_final_pending.FinalPending','migration_terminal.B'))
    g.branch('migration_finish_check');g.link(('migration_terminal.ReturnValue','migration_finish_check.condition'));g.chain('migration_finish','migration_finish_check')
    g.set('migration_finish_pending','FinalPending',B.RULE,defaults={'FinalPending':'true'});g.link(('migration_rule.BB5BombRule','migration_finish_pending.self'));g.chain('migration_finish_check','migration_finish_pending')
    g.get('migration_manager','CombatManager',B.RULE);g.link(('migration_rule.BB5BombRule','migration_manager.self'))
    g.cast('migration_manager_cast',combat.GM,pure=True);g.link(('migration_manager.CombatManager','migration_manager_cast.cast_object'))
    g.call('migration_close_combat',combat.GM,'CombatClose');g.link(('migration_manager_cast.cast_result','migration_close_combat.self'));g.chain('migration_finish_pending','migration_close_combat')

    # Keep the same searchable session name so a crashed original host can find
    # the successor through the existing joiner path.
    g.existing('migration_advertise','MigrationAdvertise')
    g.call('migration_lobby',B.ONLINE,'GetCurrentLobbyInfo')
    for i,name in enumerate(('Name','CH_MATCH')):
        node='migration_same'+str(i)
        g.call(node,B.ONLINE_TYPES,'CompareLobbyInfoStringAttribute',{'Key':name})
        g.link(('migration_lobby.ReturnValue',node+'.LobbyInfo'),(key,node+'.Value'))
    g.call('migration_advertised',MATH,'BooleanAND');g.link(('migration_same0.ReturnValue','migration_advertised.A'),('migration_same1.ReturnValue','migration_advertised.B'))
    g.branch('migration_needs_publish');g.link(('migration_advertised.ReturnValue','migration_needs_publish.condition'));g.chain('migration_advertise','migration_needs_publish')
    g.n('migration_attrs','makemap',count=2)
    for i,name in enumerate(('Name','CH_MATCH')):
        p='migration_attr'+str(i)
        g.call(p+'key',SYS,'MakeLiteralString',{'Value':name})
        g.call(p+'value',B.ONLINE_TYPES,'MakeStringLobbyAttribute');g.link((key,p+'value.Value'))
        g.link((p+'key.ReturnValue','migration_attrs.Key '+str(i)),(p+'value.ReturnValue','migration_attrs.Value '+str(i)))
    g.call('migration_update',B.UPDATE_LOBBY,'UpdateLobby',{'SessionName':'GameSession','MaxPlayers':'10',
        'bAllowJoinInProgress':'true','bLockForInviteOnly':'false'})
    g.link(('migration_attrs.Map','migration_update.Settings'),('migration_needs_publish.else','migration_update.exec'))
    g.call('migration_update_activate',B.ASYNC_BASE,'Activate');g.link(('migration_update.ReturnValue','migration_update_activate.self'))
    g.chain('migration_update','migration_update_activate')

def request_events():
    g=G();g.custom('begin','BeginMigrationRequest',[P('RuleComponent','object',**{'class':B.RULE}),P('MatchKey','string')])
    g.custom('reply','OnMigrationReply',[P('bSuccess','bool')]);return g.json()

def request_logic():
    g=G();g.existing('begin','BeginMigrationRequest');g.get('rule','Rule');g.get('key','MatchKey')
    previous='begin'
    for node,name,value in (('keep_rule','Rule','begin.RuleComponent'),('keep_key','MatchKey','begin.MatchKey')):
        g.set(node,name);g.link((value,node+'.'+name));g.chain(previous,node);previous=node
    for name,source in (('Epoch','HostEpoch'),('Activate','MigrationPending')):
        g.get('current_'+name,source,B.RULE);g.link(('rule.Rule','current_'+name+'.self'))
        g.set('capture_'+name,name);g.link(('current_'+name+'.'+source,'capture_'+name+'.'+name));g.chain(previous,'capture_'+name);previous='capture_'+name
        g.get('saved_'+name,name)
    g.call('lifespan',ACTOR,'SetLifeSpan',{'InLifespan':'3.0'});g.chain(previous,'lifespan')
    B._report_send(g,'ask',{'URL':B.REPORT_URL+'/migration','FirstSessionTimestamp':'chmigration-1'})
    g.call('operation',MATH,'SelectString',{'A':'ch_host_activate','B':'ch_host_endorse'})
    g.link(('saved_Activate.Activate','operation.bPickA'),('operation.ReturnValue','ask.EventName'),('key.MatchKey','ask.Storefront'))
    g.get('candidate','MigrationCandidate',B.RULE);g.link(('rule.Rule','candidate.self'),('candidate.MigrationCandidate','ask.Platform'))
    g.n('delegate','createevent',func='OnMigrationReply');g.link(('delegate.OutputDelegate','ask.OnResponse'));g.chain('lifespan','ask')
    g.existing('reply','OnMigrationReply')
    g.call('valid',SYS,'IsValid');g.link(('rule.Rule','valid.Object'))
    g.call('same_epoch',MATH,'EqualEqual_IntInt');g.link(('current_Epoch.HostEpoch','same_epoch.A'),('saved_Epoch.Epoch','same_epoch.B'))
    current_key,_=B._start_key(g,'callback_')
    g.call('same_key',STR,'EqualEqual_StrStr');g.link((current_key,'same_key.A'),('key.MatchKey','same_key.B'))
    previous='reply.bSuccess'
    for i,value in enumerate(('valid.ReturnValue','same_epoch.ReturnValue','same_key.ReturnValue','saved_Activate.Activate','current_Activate.MigrationPending')):
        node='guard'+str(i);g.call(node,MATH,'BooleanAND');g.link((previous,node+'.A'),(value,node+'.B'));previous=node+'.ReturnValue'
    g.branch('accept');g.link((previous,'accept.condition'));g.chain('reply','accept')
    g.set('ready','MigrationPending',B.RULE,defaults={'MigrationPending':'false'});g.link(('rule.Rule','ready.self'));g.chain('accept','ready')
    g.call('gm',GS_LIB,'GetGameMode');g.cast('cast',B.GM_BB5,pure=True);g.link(('gm.ReturnValue','cast.cast_object'))
    g.call('advertise',B.GM_BB5,'MigrationAdvertise');g.link(('cast.cast_result','advertise.self'));g.chain('ready','advertise')
    return g.json()
