'use strict';
const body=`<h2>Events</h2><div class="card"><a href="/admin/events?event=launch-2026"><h2>Lights Out Launch Tournament · $500 USD</h2></a><p id="event-schedule"></p><div class="stats" id="event-stats"></div><p class="note" id="event-review"></p><p class="note">Five eligible matches required for prizes. Staff may compete. After both tiebreakers, each tied player receives the full prize for their shared place, including fifth-place ties. Places skip after ties (1, 1, 3); total payouts may exceed $500. Payouts only by Zelle, Venmo or PayPal. No payments are sent by this console.</p></div>
<div class="bar"><input id="event-search" type="search" placeholder="Search entrant name or ID"><button class="btn" id="event-refresh">Refresh</button></div><p id="event-note" role="status"></p>
<div class="table-scroll"><table><thead><tr><th>Place</th><th>Player</th><th>Registered</th><th>Net RR</th><th>Wins / matches</th><th>Eligibility</th><th>Payout</th><th>Evidence / actions</th></tr></thead><tbody id="event-rows"></tbody></table></div>
<div class="card" id="event-support"><h2>Launch Tournament support tickets</h2><p class="note">Replies appear on the player's tournament page and in their Lights Out Admin conversation. Keep payout details out of tickets.</p><div id="event-tickets"></div></div>
<div class="card"><h2>Event operations</h2><p class="note">All actions are audited. Outages extend the event by their duration; overlapping periods count once. Enter dates in your computer's local time.</p>
<form id="event-form"><div class="bar"><select id="event-action" aria-label="Action"><option value="reply">Reply to ticket</option><option value="resolve">Resolve ticket</option><option value="disqualify">Disqualify entrant</option><option value="restore">Restore entrant</option><option value="outage">Record downtime or match-breaking issue</option><option value="announcement">Publish event notice</option><option value="confirm">Confirm winners</option><option value="reopen">Reopen results</option><option value="payout">Update payout</option></select><input id="event-target" placeholder="Player ID" aria-label="Player ID"><input id="event-ticket" placeholder="Ticket ID" aria-label="Ticket ID"></div>
<div class="bar"><label>Outage start <input id="event-start" type="datetime-local" step="1"></label><label>Outage end <input id="event-end" type="datetime-local" step="1"></label><select id="event-method" aria-label="Payout method"><option>Zelle</option><option>Venmo</option><option>PayPal</option></select><select id="event-payout" aria-label="Payout status"><option value="details_received">Valid details received privately</option><option value="paid">Paid</option></select></div>
<textarea id="event-reason" rows="3" maxlength="500" aria-label="Response or reason" placeholder="Response, evidence, reason or public notice" style="width:100%;padding:12px;background:#11151c;color:#eee;border:1px solid #333"></textarea><p><button class="btn" type="submit">Apply action</button></p></form><p id="event-result" role="status"></p></div>
<details class="card"><summary>Recent event audit history (latest 100)</summary><div id="event-audit"></div></details><script>(${require('./admin-events-ui.cjs').toString()})();</script>`;
module.exports={body};
