"""Tournament snapshots contain display data only; server receipts own scoring."""
import time
from ... import i18n
from . import register_snapshot, register_verbs

_KEYS = "title subtitle register registered signin starts_in remaining scheduled live ended review schedule prizes payout your_score net gained lost wins matches leaders player place empty upcoming refresh stale unavailable identity_conflict identity_required capacity rules timezone".split()
_COPY = {
    "en": ["Launch Tournament", "$150 USD · 1v1 Bodybomb (Paintball) · 48 hours · 3 prize places", "Register for Tournament", "You’re registered", "Sign in to register and view standings.", "Starts in", "Time remaining", "Upcoming", "LIVE", "Event ended", "Results under review. Standings may update as saved match results arrive.", "Event schedule", "Prize pool", "Payouts: Zelle, Venmo or PayPal only. All prizes are in USD.", "Your tournament", "Net RR", "RR gained", "RR lost", "Wins", "Matches", "Top 10", "Player", "Place", "No eligible results yet.", "The top 10 appears when the event starts.", "Refresh", "Showing the last available standings.", "Unable to update. Please try again shortly.", "This game account is already registered, or differs from your registered account.", "Sign in with your verified game account to register.", "Registration is temporarily unavailable. Contact the organizer.", "Register, then play ranked 1v1 Bodybomb (Paintball). Your match RR gains minus losses determine your score. Matches must start on or after both registration and the event start, and finish before the event ends. Late entry earns no retroactive credit. Placement seeding, voids and manual rank changes do not count. Ties: more event wins, then earliest time reaching the final RR total. If players remain tied, each receives the full prize for their shared place, including ties at third. The next place skips the positions occupied by the tie (1, 1, 3). Total payouts may exceed $150.", "Central time · CDT (UTC−5)"],
    "de": ["Launch-Turnier", "150 USD · 1v1 Bodybomb (Paintball) · 48 Stunden · 3 Preisplätze", "Für das Turnier anmelden", "Du bist angemeldet", "Melde dich an, um teilzunehmen und die Rangliste zu sehen.", "Start in", "Verbleibende Zeit", "Demnächst", "LIVE", "Event beendet", "Ergebnisse werden geprüft. Gespeicherte Matchergebnisse können die Rangliste noch ändern.", "Event-Zeiten", "Preisgeld", "Auszahlung nur per Zelle, Venmo oder PayPal. Alle Preise in USD.", "Dein Turnier", "Netto-RR", "RR gewonnen", "RR verloren", "Siege", "Matches", "Top 10", "Spieler", "Platz", "Noch keine gültigen Ergebnisse.", "Die Top 10 erscheinen zum Event-Start.", "Aktualisieren", "Die zuletzt verfügbaren Ergebnisse werden angezeigt.", "Aktualisierung nicht möglich. Bitte später erneut versuchen.", "Dieses Spielkonto ist bereits registriert oder weicht vom registrierten Konto ab.", "Melde dich mit deinem verifizierten Spielkonto an.", "Anmeldung vorübergehend nicht verfügbar. Kontaktiere den Veranstalter.", "Melde dich an und spiele Ranglisten-1v1 Bodybomb (Paintball). RR-Gewinne minus Verluste ergeben deine Punkte. Matches müssen nach Anmeldung und Event-Start beginnen und vor Event-Ende enden. Keine rückwirkenden Punkte bei später Anmeldung. Platzierungswerte, annullierte Matches und manuelle Rangänderungen zählen nicht. Gleichstand: mehr Event-Siege, dann frühester Zeitpunkt des endgültigen RR-Werts. Bleibt der Gleichstand bestehen, erhält jeder den vollen Preis für den gemeinsamen Platz, auch bei Platz drei. Danach werden die belegten Plätze übersprungen (1, 1, 3). Die Gesamtauszahlung kann 150 USD übersteigen.", "Central-Zeit · CDT (UTC−5)"],
    "es": ["Torneo de lanzamiento", "150 USD · 1v1 Bodybomb (Paintball) · 48 horas · 3 puestos con premio", "Registrarse en el torneo", "Ya estás registrado", "Inicia sesión para registrarte y ver la clasificación.", "Comienza en", "Tiempo restante", "Próximamente", "EN VIVO", "Evento finalizado", "Resultados en revisión. La clasificación puede cambiar al llegar resultados guardados.", "Horario del evento", "Premios", "Pagos solo por Zelle, Venmo o PayPal. Todos los premios son en USD.", "Tu torneo", "RR neto", "RR ganado", "RR perdido", "Victorias", "Partidas", "Top 10", "Jugador", "Puesto", "Aún no hay resultados válidos.", "El top 10 aparece cuando comienza el evento.", "Actualizar", "Se muestra la última clasificación disponible.", "No se pudo actualizar. Inténtalo de nuevo pronto.", "Esta cuenta de juego ya está registrada o difiere de la cuenta registrada.", "Inicia sesión con tu cuenta de juego verificada para registrarte.", "Registro temporalmente no disponible. Contacta al organizador.", "Regístrate y juega partidas clasificatorias 1v1 Bodybomb (Paintball). Tu puntuación es el RR ganado menos las pérdidas. Las partidas deben empezar tras tu registro y el inicio del evento, y terminar antes del cierre. No hay crédito retroactivo por registro tardío. No cuentan la asignación inicial de rango, partidas anuladas ni cambios manuales. Desempate: más victorias del evento y luego quien alcanzó antes el RR final. Si persiste el empate, cada jugador recibe el premio completo del puesto compartido, incluso en el tercer puesto. El siguiente puesto salta las posiciones ocupadas por el empate (1, 1, 3). El total pagado puede superar los 150 USD.", "Hora central · CDT (UTC−5)"],
    "fr": ["Tournoi de lancement", "150 USD · 1v1 Bodybomb (Paintball) · 48 heures · 3 places primées", "S’inscrire au tournoi", "Vous êtes inscrit", "Connectez-vous pour vous inscrire et voir le classement.", "Début dans", "Temps restant", "À venir", "EN DIRECT", "Événement terminé", "Résultats en cours de vérification. Le classement peut évoluer à la réception des résultats enregistrés.", "Calendrier", "Dotation", "Paiements uniquement par Zelle, Venmo ou PayPal. Tous les prix sont en USD.", "Votre tournoi", "RR net", "RR gagnés", "RR perdus", "Victoires", "Matchs", "Top 10", "Joueur", "Place", "Aucun résultat admissible pour le moment.", "Le top 10 apparaît au début de l’événement.", "Actualiser", "Affichage du dernier classement disponible.", "Actualisation impossible. Réessayez bientôt.", "Ce compte de jeu est déjà inscrit ou diffère du compte inscrit.", "Connectez-vous avec votre compte de jeu vérifié pour vous inscrire.", "Inscription temporairement indisponible. Contactez l’organisateur.", "Inscrivez-vous puis jouez en classé 1v1 Bodybomb (Paintball). Votre score correspond aux RR gagnés moins les pertes. Les matchs doivent commencer après l’inscription et le début de l’événement, et finir avant sa clôture. Aucun crédit rétroactif. Le placement initial, les matchs annulés et les changements manuels de rang sont exclus. Égalités : plus de victoires, puis premier joueur à atteindre le total RR final. Si l’égalité persiste, chaque joueur reçoit la totalité du prix de sa place partagée, y compris à la troisième place. Les places occupées par l’égalité sont ensuite sautées (1, 1, 3). Le total versé peut dépasser 150 USD.", "Heure du Centre · CDT (UTC−5)"],
    "pt": ["Torneio de lançamento", "150 USD · 1v1 Bodybomb (Paintball) · 48 horas · 3 posições premiadas", "Inscrever-se no torneio", "Você está inscrito", "Entre para se inscrever e ver a classificação.", "Começa em", "Tempo restante", "Em breve", "AO VIVO", "Evento encerrado", "Resultados em análise. A classificação pode mudar com a chegada de resultados salvos.", "Horário do evento", "Premiação", "Pagamentos apenas por Zelle, Venmo ou PayPal. Todos os prêmios em USD.", "Seu torneio", "RR líquido", "RR ganho", "RR perdido", "Vitórias", "Partidas", "Top 10", "Jogador", "Posição", "Ainda não há resultados válidos.", "O top 10 aparece no início do evento.", "Atualizar", "Exibindo a última classificação disponível.", "Não foi possível atualizar. Tente novamente em breve.", "Esta conta de jogo já está inscrita ou difere da conta inscrita.", "Entre com sua conta de jogo verificada para se inscrever.", "Inscrições temporariamente indisponíveis. Contate o organizador.", "Inscreva-se e jogue partidas ranqueadas 1v1 Bodybomb (Paintball). Seu total é o RR ganho menos as perdas. As partidas devem começar após a inscrição e o início do evento e terminar antes do encerramento. Não há crédito retroativo. Colocação inicial, partidas anuladas e alterações manuais de rank não contam. Desempate: mais vitórias no evento, depois quem atingiu antes o total final. Se o empate persistir, cada jogador recebe o prêmio integral da posição compartilhada, inclusive na terceira posição. A classificação seguinte pula as posições ocupadas pelo empate (1, 1, 3). O total pago pode ultrapassar 150 USD.", "Horário central · CDT (UTC−5)"],
    "ru": ["Стартовый турнир", "150 USD · 1v1 Bodybomb (Paintball) · 48 часов · 3 призовых места", "Зарегистрироваться на турнир", "Вы зарегистрированы", "Войдите, чтобы зарегистрироваться и увидеть таблицу.", "До начала", "Осталось времени", "Скоро", "ИДЁТ", "Событие завершено", "Результаты проверяются. Таблица может обновиться при поступлении сохранённых результатов матчей.", "Расписание", "Призовой фонд", "Выплаты только через Zelle, Venmo или PayPal. Все призы в USD.", "Ваш турнир", "Итоговый RR", "RR получено", "RR потеряно", "Победы", "Матчи", "Топ-10", "Игрок", "Место", "Подходящих результатов пока нет.", "Топ-10 появится после начала события.", "Обновить", "Показана последняя доступная таблица.", "Не удалось обновить. Попробуйте позже.", "Этот игровой аккаунт уже зарегистрирован или отличается от зарегистрированного.", "Войдите с подтверждённым игровым аккаунтом для регистрации.", "Регистрация временно недоступна. Обратитесь к организатору.", "Зарегистрируйтесь и играйте рейтинговые матчи 1 на 1 Bodybomb (Paintball). Счёт - заработанные RR минус потери. Матчи должны начаться после регистрации и старта события и завершиться до его окончания. Прошлые матчи не засчитываются. Начальный ранг, аннулированные матчи и ручные изменения ранга не учитываются. При равенстве: больше побед, затем более раннее достижение итогового RR. Если равенство сохраняется, каждый получает полный приз за общее место, включая третье. Следующее место учитывает число игроков с одинаковым результатом (1, 1, 3). Общая сумма выплат может превысить 150 USD.", "Центральное время · CDT (UTC−5)"],
    "zh": ["开服锦标赛", "150 美元 · 1v1 Bodybomb (Paintball) · 48 小时 · 3 个获奖名次", "报名锦标赛", "已报名", "登录后即可报名并查看排名。", "距离开始", "剩余时间", "即将开始", "进行中", "活动已结束", "结果审核中。已保存的比赛结果到达后，排名可能更新。", "活动时间", "奖金池", "仅通过 Zelle、Venmo 或 PayPal 支付。所有奖金均为美元。", "你的锦标赛", "净 RR", "获得 RR", "损失 RR", "胜场", "比赛", "前 10 名", "玩家", "名次", "暂无符合条件的成绩。", "活动开始后显示前 10 名。", "刷新", "正在显示最近可用的排名。", "无法更新，请稍后重试。", "此游戏账号已报名，或与报名时的账号不同。", "请使用已验证的游戏账号登录并报名。", "报名暂不可用，请联系主办方。", "报名后参加 1v1 Bodybomb (Paintball) 排位赛。得分为获得的 RR 减去损失的 RR。比赛必须在报名及活动开始后开赛，并在活动结束前完成。迟报名不追溯先前成绩。定级初始分数、作废比赛和手动段位调整不计入。平分时先比较活动胜场，再比较首次达到最终 RR 总分的时间。若仍并列，每位玩家均获得并列名次的全额奖金，第三名并列也适用。后续名次跳过并列占用的位置（1、1、3）。总奖金支出可能超过 150 美元。", "美国中部时间 · CDT（UTC−5）"],
}
STRINGS = {code: dict(zip(_KEYS, values, strict=True)) for code, values in _COPY.items()}
for _code, _units in {"en": "DAYS : HRS : MIN : SEC", "de": "TAGE : STD : MIN : SEK",
                     "es": "DÍAS : HRS : MIN : SEG", "fr": "JOURS : H : MIN : SEC",
                     "pt": "DIAS : H : MIN : SEG", "ru": "ДНИ : Ч : МИН : СЕК",
                     "zh": "天 : 时 : 分 : 秒"}.items():
    STRINGS[_code]["clock_units"] = _units
for _code, _notice in {
    "en": "By playing in this tournament, you agree to receive any winnings through Zelle, Venmo, or PayPal.",
    "de": "Mit deiner Teilnahme an diesem Turnier erklärst du dich damit einverstanden, Gewinne über Zelle, Venmo oder PayPal zu erhalten.",
    "es": "Al jugar en este torneo, aceptas recibir cualquier premio a través de Zelle, Venmo o PayPal.",
    "fr": "En participant à ce tournoi, vous acceptez de recevoir vos éventuels gains via Zelle, Venmo ou PayPal.",
    "pt": "Ao jogar neste torneio, você concorda em receber eventuais prêmios por Zelle, Venmo ou PayPal.",
    "ru": "Участвуя в этом турнире, вы соглашаетесь получать возможные призовые через Zelle, Venmo или PayPal.",
    "zh": "参加本锦标赛即表示你同意通过 Zelle、Venmo 或 PayPal 接收任何奖金。",
}.items():
    STRINGS[_code]["payout_agreement"] = _notice
for _code, _labels in {
    "en": ["Tournament winners", "Prize pending review", "Final standings"],
    "de": ["Turniergewinner", "Preis wird geprüft", "Endstand"],
    "es": ["Ganadores del torneo", "Premio pendiente de revisión", "Clasificación final"],
    "fr": ["Gagnants du tournoi", "Prix en cours de vérification", "Classement final"],
    "pt": ["Vencedores do torneio", "Prêmio em análise", "Classificação final"],
    "ru": ["Победители турнира", "Приз на проверке", "Итоговая таблица"],
    "zh": ["锦标赛获奖者", "奖金待审核", "最终排名"],
}.items():
    STRINGS[_code].update(zip(["winners", "prize_review", "final_standings"], _labels))
for _code, _label in {"en": "Tournament entrants: {count}", "de": "Turnierteilnehmer: {count}", "es": "Participantes del torneo: {count}", "fr": "Participants au tournoi : {count}", "pt": "Participantes do torneio: {count}", "ru": "Участники турнира: {count}", "zh": "锦标赛报名人数：{count}"}.items():
    STRINGS[_code]["entrants"] = _label
for _code, _labels in {
    "en": ["Payout status", "Awaiting details privately", "Details received", "Paid", "On hold for review", "Payment due", "Fair-play report"],
    "de": ["Auszahlungsstatus", "Private Angaben ausstehend", "Angaben erhalten", "Bezahlt", "Zur Prüfung zurückgestellt", "Zahlung fällig", "Fair-Play-Meldung"],
    "es": ["Estado del pago", "Esperando datos por privado", "Datos recibidos", "Pagado", "En espera de revisión", "Fecha límite de pago", "Reporte de juego limpio"],
    "fr": ["État du paiement", "Coordonnées privées attendues", "Coordonnées reçues", "Payé", "En attente de vérification", "Paiement dû", "Signalement de fair-play"],
    "pt": ["Status do pagamento", "Aguardando dados em privado", "Dados recebidos", "Pago", "Em análise", "Prazo de pagamento", "Denúncia de jogo limpo"],
    "ru": ["Статус выплаты", "Ожидаются данные в личном сообщении", "Данные получены", "Выплачено", "Приостановлено для проверки", "Срок выплаты", "Нарушение честной игры"],
    "zh": ["付款状态", "等待私下提供收款信息", "已收到收款信息", "已支付", "暂停并等待审核", "付款截止日期", "公平竞赛举报"],
}.items():
    STRINGS[_code].update(zip("payout_status awaiting_details details_received paid on_hold payment_due fair_play_report".split(), _labels, strict=True))
_EXTRA_KEYS = "policies fair_play outage_policy ledger counted excluded support category match_id message send ticket_sent open resolved missing_rr appeal outage other participant winner confirmed qualification gap extension before_registration before_start after_cutoff account_mismatch voided not_ranked unverified share disqualified".split()
_EXTRA = {
 "en": ["Five completed eligible matches are required for cash prizes. Staff may compete. Disputes must be filed within 24 hours of the event ending. Winners are confirmed after review. Payouts are due within seven days of receiving valid payout details privately.", "Cheating, smurfing, account sharing, boosting, win trading and intentional throwing are prohibited and may result in disqualification. Organizer decisions and appeals are recorded.", "For any period Lights Out is down or has match-breaking issues, an equivalent amount of time will be added to the tournament. Verified incidents and the revised deadline will be shown here. Overlapping incidents count once.", "Your match ledger", "Counted", "Excluded", "Tournament support", "Issue type", "Match ID (if applicable)", "Describe the issue. Do not include payment details.", "Send ticket", "Ticket sent to the event admins.", "Open", "Resolved", "Missing RR", "Appeal", "Outage / match issue", "Other", "Launch participant", "Launch winner", "Winners confirmed", "{count} more eligible matches needed for prizes", "{count} RR behind third place", "{count} minutes added for service issues", "Started before registration", "Started before the event", "Finished after the cutoff", "Game account mismatch", "Voided match", "Not ranked 1v1 Bodybomb (Paintball)", "No verified completed result", "Share event", "Disqualified"],
 "de": ["Fünf gültige Matches sind für Geldpreise erforderlich. Mitarbeiter dürfen teilnehmen. Beschwerden müssen innerhalb von 24 Stunden nach Event-Ende eingehen. Gewinner werden nach Prüfung bestätigt. Auszahlung innerhalb von sieben Tagen nach privatem Erhalt gültiger Zahlungsdaten.", "Cheating, Smurfing, Account-Sharing, Boosting, abgesprochene Siege und absichtliches Verlieren sind verboten und können zur Disqualifikation führen. Entscheidungen und Einsprüche werden dokumentiert.", "Ausfallzeiten von Lights Out oder Zeiten mit spielverhindernden Problemen werden vollständig an das Turnier angehängt. Bestätigte Vorfälle und die neue Frist stehen hier. Überschneidungen zählen einmal.", "Deine Match-Historie", "Gezählt", "Ausgeschlossen", "Turnier-Support", "Problemtyp", "Match-ID (falls vorhanden)", "Beschreibe das Problem. Keine Zahlungsdaten angeben.", "Ticket senden", "Ticket an die Event-Admins gesendet.", "Offen", "Gelöst", "Fehlende RR", "Einspruch", "Ausfall / Matchproblem", "Sonstiges", "Launch-Teilnehmer", "Launch-Gewinner", "Gewinner bestätigt", "Noch {count} gültige Matches für Preise", "{count} RR hinter Platz drei", "{count} Minuten wegen Störungen hinzugefügt", "Vor Anmeldung gestartet", "Vor Event-Start gestartet", "Nach Frist beendet", "Anderes Spielkonto", "Annulliertes Match", "Kein Ranglisten-1v1 Bodybomb (Paintball)", "Kein bestätigtes Endergebnis", "Event teilen", "Disqualifiziert"],
 "es": ["Se requieren cinco partidas válidas para ganar premios. El personal puede competir. Las disputas deben enviarse en las 24 horas posteriores al cierre. Ganadores confirmados tras la revisión. Pago en siete días desde la recepción privada de datos de pago válidos.", "Se prohíben trampas, smurfing, compartir cuentas, boosting, intercambiar victorias y perder intencionadamente. Pueden causar descalificación. Se registran decisiones y apelaciones.", "Todo período de caída de Lights Out o de problemas que impidan jugar se añadirá a la duración del torneo. Aquí se mostrarán los incidentes verificados y el nuevo cierre. Los períodos superpuestos cuentan una vez.", "Tu historial del evento", "Contada", "Excluida", "Soporte del torneo", "Tipo de problema", "ID de partida (si procede)", "Describe el problema. No incluyas datos de pago.", "Enviar solicitud", "Solicitud enviada a los administradores.", "Abierta", "Resuelta", "Falta RR", "Apelación", "Caída / problema de partida", "Otro", "Participante de lanzamiento", "Ganador de lanzamiento", "Ganadores confirmados", "Faltan {count} partidas válidas para premios", "A {count} RR del tercer puesto", "{count} minutos añadidos por incidencias", "Empezó antes del registro", "Empezó antes del evento", "Terminó después del cierre", "Cuenta de juego distinta", "Partida anulada", "No es clasificatoria 1v1 Bodybomb (Paintball)", "Sin resultado final verificado", "Compartir evento", "Descalificado"],
 "fr": ["Cinq matchs admissibles sont requis pour gagner un prix. Le personnel peut participer. Les réclamations doivent être déposées dans les 24 heures après la fin. Gagnants confirmés après vérification. Paiement sous sept jours après réception privée de coordonnées valides.", "Triche, smurfing, partage de compte, boosting, victoires arrangées et défaites volontaires sont interdits et peuvent entraîner une disqualification. Décisions et recours sont enregistrés.", "Toute indisponibilité de Lights Out ou période de problèmes empêchant les matchs sera ajoutée à la durée du tournoi. Les incidents vérifiés et la nouvelle échéance seront affichés ici. Les chevauchements comptent une seule fois.", "Votre historique de matchs", "Compté", "Exclu", "Assistance du tournoi", "Type de problème", "ID du match (si applicable)", "Décrivez le problème. Ne saisissez aucune coordonnée de paiement.", "Envoyer la demande", "Demande envoyée aux administrateurs.", "Ouverte", "Résolue", "RR manquants", "Recours", "Panne / problème de match", "Autre", "Participant du lancement", "Gagnant du lancement", "Gagnants confirmés", "Encore {count} matchs admissibles pour les prix", "À {count} RR de la troisième place", "{count} minutes ajoutées pour incidents", "Commencé avant l’inscription", "Commencé avant l’événement", "Terminé après la clôture", "Compte de jeu différent", "Match annulé", "Hors classé 1v1 Bodybomb (Paintball)", "Aucun résultat final vérifié", "Partager l’événement", "Disqualifié"],
 "pt": ["São necessárias cinco partidas válidas para prêmios. A equipe pode competir. Contestações devem chegar em até 24 horas após o fim. Vencedores confirmados após análise. Pagamento em sete dias após receber dados válidos em privado.", "Trapaças, smurfing, compartilhamento de contas, boosting, troca de vitórias e derrotas intencionais são proibidos e podem causar desclassificação. Decisões e recursos ficam registrados.", "Todo período em que Lights Out ficar fora do ar ou tiver problemas que impeçam partidas será acrescentado ao torneio. Incidentes verificados e o novo prazo aparecerão aqui. Sobreposições contam uma vez.", "Seu histórico do evento", "Contada", "Excluída", "Suporte do torneio", "Tipo de problema", "ID da partida (se aplicável)", "Descreva o problema. Não inclua dados de pagamento.", "Enviar chamado", "Chamado enviado aos administradores.", "Aberto", "Resolvido", "RR ausente", "Recurso", "Queda / problema de partida", "Outro", "Participante do lançamento", "Vencedor do lançamento", "Vencedores confirmados", "Faltam {count} partidas válidas para prêmios", "{count} RR atrás do terceiro lugar", "{count} minutos adicionados por incidentes", "Iniciada antes da inscrição", "Iniciada antes do evento", "Encerrada após o prazo", "Conta de jogo diferente", "Partida anulada", "Não é ranqueada 1v1 Bodybomb (Paintball)", "Sem resultado final verificado", "Compartilhar evento", "Desclassificado"],
 "ru": ["Для призов нужны пять зачтённых матчей. Сотрудники могут участвовать. Жалобы принимаются в течение 24 часов после окончания. Победители подтверждаются после проверки. Выплата - в течение семи дней после получения корректных реквизитов в личном порядке.", "Запрещены читы, смурфинг, общий доступ к аккаунтам, бустинг, обмен победами и намеренные поражения. Возможна дисквалификация. Решения и апелляции фиксируются.", "Любой период недоступности Lights Out или проблем, мешающих проводить матчи, будет добавлен к длительности турнира. Подтверждённые сбои и новый срок появятся здесь. Пересечения учитываются один раз.", "Ваши матчи турнира", "Зачтён", "Исключён", "Поддержка турнира", "Тип проблемы", "ID матча (если есть)", "Опишите проблему. Не указывайте платёжные реквизиты.", "Отправить обращение", "Обращение отправлено администраторам.", "Открыто", "Решено", "Не начислены RR", "Апелляция", "Сбой / проблема матча", "Другое", "Участник запуска", "Победитель запуска", "Победители подтверждены", "Для призов нужно ещё {count} матчей", "До третьего места {count} RR", "Добавлено {count} минут из-за сбоев", "Начался до регистрации", "Начался до события", "Завершён после срока", "Другой игровой аккаунт", "Аннулированный матч", "Не рейтинговый 1 на 1 Bodybomb (Paintball)", "Нет проверенного результата", "Поделиться событием", "Дисквалифицирован"],
 "zh": ["获得奖金需完成五场有效比赛。工作人员可以参赛。争议须在活动结束后 24 小时内提交，审核后确认获奖者。私下收到有效收款信息后七天内付款。", "禁止作弊、小号参赛、共享账号、代练、互刷胜场及故意输掉比赛，违者可能被取消资格。处理决定和申诉均会记录。", "Lights Out 停机或出现导致比赛无法正常进行的问题时，相应时长将添加到锦标赛期限。已核实的故障和更新后的截止时间将在此显示。重叠时段只计算一次。", "你的比赛记录", "已计入", "未计入", "锦标赛支持", "问题类型", "比赛 ID（如适用）", "请描述问题，不要填写收款信息。", "提交工单", "工单已发送给活动管理员。", "待处理", "已解决", "RR 缺失", "申诉", "停机／比赛问题", "其他", "开服活动参与者", "开服活动获奖者", "获奖者已确认", "还需完成 {count} 场有效比赛才能获奖", "距第三名还差 {count} RR", "因故障延长 {count} 分钟", "报名之前开始", "活动之前开始", "截止之后结束", "游戏账号不匹配", "比赛作废", "非 1v1 Bodybomb (Paintball) 排位赛", "无已验证的最终结果", "分享活动", "已取消资格"],
}
for _code, _values in _EXTRA.items():
    STRINGS[_code].update(zip(_EXTRA_KEYS, _values, strict=True))

for _code, _text in {
    "en": "Cheater detected; RR results reverted", "de": "Cheater erkannt; RR-Ergebnisse rückgängig gemacht",
    "es": "Tramposo detectado; resultados de RR revertidos", "fr": "Tricheur détecté ; résultats RR annulés",
    "pt": "Trapaceiro detectado; resultados de RR revertidos", "ru": "Обнаружен читер; изменения RR отменены",
    "zh": "检测到作弊者；RR 结果已撤销",
}.items():
    STRINGS[_code]["cheater_reverted"] = _text

# Explicit entry requirements and evidence channels on every localized rules page.
for _code, (_placement, _footage, _label) in {
    "en": ("You must complete your ranked 1v1 Bodybomb (Paintball) placement matches and receive a 1v1 rank first. Placement matches do not count toward tournament RR or the five eligible matches required for prizes.", "Recorded footage of any cheaters may be submitted in our Discord or on our Reddit page for quicker action.", "Placement match"),
    "de": ("Du musst zuerst deine Platzierungsspiele in 1v1 Bodybomb (Paintball) abschließen und einen 1v1-Rang erhalten. Platzierungsspiele zählen weder für Turnier-RR noch für die fünf für Preise erforderlichen Matches.", "Aufnahmen von Cheatern können für eine schnellere Bearbeitung in unserem Discord oder auf unserer Reddit-Seite eingereicht werden.", "Platzierungsspiel"),
    "es": ("Primero debes completar tus partidas de posicionamiento de 1v1 Bodybomb (Paintball) y obtener un rango 1v1. Estas partidas no cuentan para los RR del torneo ni para las cinco partidas válidas requeridas para premios.", "Puedes enviar grabaciones de tramposos en nuestro Discord o en nuestra página de Reddit para que actuemos más rápido.", "Partida de posicionamiento"),
    "fr": ("Vous devez d’abord terminer vos matchs de placement en 1v1 Bodybomb (Paintball) et obtenir un rang 1v1. Ces matchs ne comptent ni pour les RR du tournoi ni pour les cinq matchs requis pour les prix.", "Des vidéos de tricheurs peuvent être envoyées sur notre Discord ou notre page Reddit pour une intervention plus rapide.", "Match de placement"),
    "pt": ("Primeiro, conclua suas partidas de colocação de 1v1 Bodybomb (Paintball) e receba um rank 1v1. Elas não contam para os RR do torneio nem para as cinco partidas válidas exigidas para prêmios.", "Gravações de trapaceiros podem ser enviadas no nosso Discord ou na nossa página do Reddit para agilizar a ação.", "Partida de colocação"),
    "ru": ("Сначала завершите калибровочные матчи в 1 на 1 Bodybomb (Paintball) и получите ранг 1 на 1. Эти матчи не учитываются в RR турнира и в пяти зачётных матчах, необходимых для призов.", "Видеозаписи с читерами можно отправить в наш Discord или на нашу страницу Reddit для более быстрого рассмотрения.", "Калибровочный матч"),
    "zh": ("你必须先完成 1v1 Bodybomb (Paintball) 定级赛并获得 1v1 段位。定级赛不计入锦标赛 RR，也不计入获得奖金所需的五场有效比赛。", "可在我们的 Discord 或 Reddit 页面提交作弊者的录像，以便更快处理。", "定级赛"),
}.items():
    STRINGS[_code]["rules"] = _placement + " " + STRINGS[_code]["rules"]
    STRINGS[_code]["fair_play"] += " " + _footage
    STRINGS[_code]["placement"] = _label

# Solo queue guidance applies to this event's independent 1v1 ladder.
for _code, _notice in {
    "en": "Select ranked 1v1 Bodybomb (Paintball) and queue solo. Leave any party before queuing. Existing tournament registrations are kept.",
    "de": "Wähle Ranglisten-1v1 Bodybomb (Paintball) und suche allein. Verlasse vorher jede Gruppe. Bestehende Turnieranmeldungen bleiben erhalten.",
    "es": "Selecciona 1v1 Bodybomb (Paintball) clasificatorio y entra a la cola solo. Sal de cualquier grupo antes. Se conservan las inscripciones existentes.",
    "fr": "Sélectionnez 1v1 Bodybomb (Paintball) classé et lancez la recherche en solo. Quittez tout groupe auparavant. Les inscriptions existantes sont conservées.",
    "pt": "Selecione 1v1 Bodybomb (Paintball) ranqueado e entre na fila solo. Saia de qualquer grupo antes. As inscrições existentes são mantidas.",
    "ru": "Выберите рейтинговый режим 1 на 1 Bodybomb (Paintball) и встаньте в очередь в одиночку. Сначала выйдите из группы. Существующие регистрации на турнир сохраняются.",
    "zh": "选择 1v1 Bodybomb (Paintball) 排位并单人匹配。匹配前请退出任何队伍。现有锦标赛报名继续有效。",
}.items():
    STRINGS[_code]["rules"] = _notice + " " + STRINGS[_code]["rules"]

for _code, _notice in {
    "en": "Due to low registrations, the 5v5 Bodybomb tournament is postponed until a later date. In return, the event will be replaced with a 1v1 Bodybomb (Paintball) tournament. This will allow users to have a better chance at finding games and participating",
    "de": "Wegen der geringen Zahl an Anmeldungen wird das 5v5-Bodybomb-Turnier auf einen späteren Zeitpunkt verschoben. Stattdessen findet ein 1v1-Bodybomb-Turnier (Paintball) statt. So haben Spieler bessere Chancen, Matches zu finden und teilzunehmen.",
    "es": "Debido al bajo número de inscripciones, el torneo de Bodybomb 5v5 se pospone para una fecha posterior. En su lugar, el evento se sustituirá por un torneo de Bodybomb 1v1 (Paintball). Así, los jugadores tendrán más posibilidades de encontrar partidas y participar.",
    "fr": "En raison du faible nombre d’inscriptions, le tournoi Bodybomb 5v5 est reporté à une date ultérieure. Il sera remplacé par un tournoi Bodybomb 1v1 (Paintball). Les joueurs auront ainsi plus de chances de trouver des matchs et de participer.",
    "pt": "Devido ao baixo número de inscrições, o torneio de Bodybomb 5v5 foi adiado para uma data posterior. Em seu lugar, o evento será substituído por um torneio de Bodybomb 1v1 (Paintball). Assim, os jogadores terão mais chances de encontrar partidas e participar.",
    "ru": "Из-за небольшого числа регистраций турнир Bodybomb 5 на 5 переносится на более позднюю дату. Вместо него пройдёт турнир Bodybomb 1 на 1 (Paintball). Так игрокам будет проще найти матчи и принять участие.",
    "zh": "由于报名人数较少，5v5 Bodybomb 锦标赛将推迟至日后举行。本次活动将改为 1v1 Bodybomb (Paintball) 锦标赛。这样玩家将更容易找到比赛并参与活动。",
}.items():
    STRINGS[_code]["format_notice"] = _notice

for _code, _notice in {
    "en": "The organizer will contact confirmed winners directly through Lights Out’s in-client messaging system to arrange their payout.",
    "de": "Der Veranstalter kontaktiert bestätigte Gewinner direkt über das Nachrichtensystem im Lights-Out-Client, um die Auszahlung zu vereinbaren.",
    "es": "El organizador contactará directamente a los ganadores confirmados mediante el sistema de mensajes del cliente de Lights Out para coordinar el pago.",
    "fr": "L’organisateur contactera directement les gagnants confirmés via la messagerie du client Lights Out pour organiser leur paiement.",
    "pt": "O organizador entrará em contato diretamente com os vencedores confirmados pelo sistema de mensagens do cliente Lights Out para combinar o pagamento.",
    "ru": "Организатор свяжется с подтверждёнными победителями напрямую через сообщения в клиенте Lights Out, чтобы согласовать выплату.",
    "zh": "主办方将通过 Lights Out 客户端内的消息系统直接联系已确认的获奖者，安排奖金发放。",
}.items():
    STRINGS[_code]["policies"] = _notice + " " + STRINGS[_code]["policies"]

@register_snapshot("tournament")
def snapshot(session, panel):
    data = dict(getattr(session, "tournament_data", None) or {})
    received = getattr(session, "tournament_received", 0.0)
    if received and data.get("server_now"):
        data["server_now"] += max(0, time.monotonic() - received) * 1000
    return {"tournament": {"data": data or None, "signed_in": bool(getattr(session, "me", None)),
        "identity": (getattr(session, "me", None) or {}).get("player_id") or (getattr(session, "me", None) or {}).get("steam_id") or "",
        "loading": bool(getattr(session, "tournament_loading", False)),
        "ticket_seq": getattr(session, "tournament_ticket_seq", 0),
        "error": getattr(session, "tournament_error", ""), "language": i18n.get_language(),
        "strings": STRINGS.get(i18n.get_language(), STRINGS["en"])}}

register_verbs("tournament", {
    "tournament_refresh": lambda panel: panel.post(panel.session.refresh_tournament),
    "tournament_register": lambda panel: panel.post(panel.session.register_tournament),
    "tournament_support": lambda panel, category, match_id, message: panel.post(lambda: panel.session.send_tournament_support(category, match_id, message)),
})
